# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170427_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='domain_id',
            new_name='domain',
        ),
    ]
