# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 16:09
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='disabled',
        ),
        migrations.AlterField(
            model_name='record',
            name='domain_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Domain'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='domain_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Domain'),
        ),
    ]
