# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170213_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='type',
            field=models.CharField(default='NATIVE', max_length=6),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone_templ_id',
            field=models.IntegerField(default=0),
        ),
    ]
