# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170216_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='domain_id',
            new_name='domain',
        ),
    ]
